apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: confluent-cloud-provision
  title: Provision Confluent Cloud Environment + Cluster
  description: >
    A template to generate or update Terraform config for a new Confluent Cloud environment + cluster.
spec:
  owner: team-xyz
  type: template

  parameters:
    - title: Confluent Cloud Settings
      properties:
        environment_name:
          title: Environment Name
          type: string
          description: Name of the new Confluent Cloud Environment
          default: dev-environment
        cluster_name:
          title: Cluster Name
          type: string
          description: Name of the new Confluent Cloud Kafka cluster
          default: dev-cluster


steps:
   - id: fetch-base
     name: Fetch Base
     action: fetch:template
     input:
        url: ./skeleton
        values:
          environment_name: ${{ parameters.environment_name }}
          cluster_name: ${{ parameters.cluster_name }}
   - id: commit
     name: Commit changes back to GitHub
     action: github:publish:repository
     input:
        repoUrl: github.com?owner=dwessendorf&repo=confluent-self-service-with-backstage-part1
        branch: main
        filepath: .
        token: ${{ secrets.GITHUB_TOKEN }}
     output:
       environmentName: ${{ parameters.environment_name }}
       clusterName: ${{ parameters.cluster_name }}
