name: "Terraform Deploy"

on:
  push:
    paths:
      - 'terraform/**'
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      CONFLUENT_CLOUD_API_KEY: ${{ secrets.CONFLUENT_CLOUD_API_KEY }}
      CONFLUENT_CLOUD_API_SECRET: ${{ secrets.CONFLUENT_CLOUD_API_SECRET }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.0.0

      - name: Initialize Terraform
        working-directory: terraform/environments/dev
        run: terraform init

      - name: Validate Terraform
        working-directory: terraform/environments/dev
        run: terraform validate

      - name: Plan Terraform
        working-directory: terraform/environments/dev
        run: terraform plan -out=tfplan

      - name: Apply Terraform
        if: github.event_name == 'push'
        working-directory: terraform/environments/dev
        run: terraform apply -auto-approve tfplan
